"""Domain exception hierarchy."""
from typing import Any


class AegisBaseError(Exception):
    """Root exception for all Aegis domain errors."""

    def __init__(self, message: str, **context: Any) -> None:
        super().__init__(message)
        self.message = message
        self.context = context


# --- Inference ---
class ModelNotFoundError(AegisBaseError): ...
class InferenceError(AegisBaseError): ...
class ModelLoadError(AegisBaseError): ...

# --- Knowledge / Document ---
class DocumentNotFoundError(AegisBaseError): ...
class DocumentParseError(AegisBaseError): ...
class IndexError(AegisBaseError): ...

# --- Security ---
class AuthenticationError(AegisBaseError): ...
class AuthorizationError(AegisBaseError): ...
class TokenExpiredError(AegisBaseError): ...

# --- Memory ---
class SessionNotFoundError(AegisBaseError): ...

# --- Plugin ---
class PluginLoadError(AegisBaseError): ...
class PluginPermissionError(AegisBaseError): ...

# --- Training ---
class TrainingJobError(AegisBaseError): ...

# --- Config ---
class ConfigError(AegisBaseError): ...
