"""First-run initialisation script for air-gapped Aegis deployment.

Usage (run once, before starting the backend):
    python scripts/init_local.py

What it does
------------
1. Creates all required local directories.
2. Generates (or verifies) the AES-256-GCM master key in keys/.
3. Runs Alembic migrations to initialise the SQLite database.
4. Seeds default roles and feature flags if the DB is empty.
5. Writes a local .env if one does not already exist.

No internet access required or used.
"""
from __future__ import annotations

import asyncio
import os
import sys
from pathlib import Path

# Ensure project root is on sys.path when run directly
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))


DIRS_TO_CREATE = [
    "data/db",
    "data/documents",
    "data/models",
    "data/embeddings",
    "data/logs",
    "data/backups",
    "config",
    "keys",
    "models",
]

DEFAULT_ENV = """
# Aegis — local environment (auto-generated by init_local.py)
# Edit as needed; never commit this file.

DATABASE_URL=sqlite+aiosqlite:///./data/db/aegis.db
SECRET_KEY=REPLACE_WITH_RANDOM_SECRET_MIN_32_CHARS
DEBUG=false
LOG_LEVEL=INFO
DATA_DIR=./data
MODELS_DIR=./models
KEYS_DIR=./keys
CONFIG_DIR=./config
""".lstrip()


def create_dirs() -> None:
    print("[init] Creating local directories...")
    for d in DIRS_TO_CREATE:
        Path(d).mkdir(parents=True, exist_ok=True)
        print(f"  ✓ {d}")


def ensure_env() -> None:
    env_path = Path(".env")
    if env_path.exists():
        print("[init] .env already exists — skipping.")
        return
    env_path.write_text(DEFAULT_ENV)
    print("[init] .env created — review and update SECRET_KEY before production use.")


def ensure_master_key() -> None:
    from backend.infrastructure.adapters.encryption import EncryptionService
    key_dir = os.environ.get("KEYS_DIR", "keys")
    enc = EncryptionService(key_dir=key_dir)
    key_path = Path(key_dir) / "aegis_master.key"
    print(f"[init] Master key: {key_path} ({'generated' if not key_path.exists() else 'loaded'})")
    # Instantiating the service creates the key if absent
    _ = enc
    print("  ✓ Encryption key ready.")


def run_migrations() -> None:
    print("[init] Running Alembic migrations...")
    import subprocess
    result = subprocess.run(
        [
            sys.executable, "-m", "alembic",
            "-c", "backend/infrastructure/db/migrations/alembic.ini",
            "upgrade", "head",
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        print("  ⚠️ Alembic error (DB may already be initialised):\n", result.stderr)
    else:
        print("  ✓ Migrations applied.")


async def seed_defaults() -> None:
    """Insert default roles and global feature flags if DB is empty."""
    from sqlmodel.ext.asyncio.session import AsyncSession
    from sqlalchemy.orm import sessionmaker
    from backend.infrastructure.db.engine import get_engine
    from backend.domain.models import Role
    from sqlmodel import select

    engine = get_engine()
    factory = sessionmaker(bind=engine, class_=AsyncSession, expire_on_commit=False)
    async with factory() as session:
        existing = await session.exec(select(Role))
        if existing.first() is not None:
            print("[init] Default roles already seeded — skipping.")
            return
        default_roles = [
            Role(name="admin", description="Full platform access"),
            Role(name="editor", description="Create and edit content"),
            Role(name="viewer", description="Read-only access"),
        ]
        for role in default_roles:
            session.add(role)
        await session.commit()
        print(f"  ✓ Seeded {len(default_roles)} default roles.")

    # Default feature flags via ConfigManager
    from backend.infrastructure.adapters.config_manager import ConfigManager
    from backend.infrastructure.adapters.encryption import EncryptionService
    config_dir = os.environ.get("CONFIG_DIR", "config")
    key_dir = os.environ.get("KEYS_DIR", "keys")
    enc = EncryptionService(key_dir=key_dir)
    cfg = ConfigManager(encryption=enc, config_dir=config_dir)
    if cfg.get("global.seeded") != "yes":
        cfg.set("global.seeded", "yes")
        cfg.set("feature_flags.speech", False)
        cfg.set("feature_flags.translation", False)
        cfg.set("feature_flags.timeseries", False)
        cfg.set("feature_flags.training", False)
        cfg.save()
        print("  ✓ Default feature flags written to config.")


def main() -> None:
    print("\n▶ Aegis — Local Init Script")
    print("=" * 40)
    create_dirs()
    ensure_env()

    # Load .env before anything else
    try:
        from dotenv import load_dotenv
        load_dotenv()
    except ImportError:
        pass

    ensure_master_key()
    run_migrations()
    asyncio.run(seed_defaults())
    print("\n✔ Init complete. Start the backend with: uvicorn backend.main:app --reload")


if __name__ == "__main__":
    main()
